name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CI: true

jobs:
  run:
    name: Node ${{ matrix.node }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node:
          - 6
          - 8
          - 10
          - 12
          - 14
        exclude:
          # Excludes nodejs v12 and v14 on windows
          # https://github.com/nodejs/node/issues/34514
          # It was patched in nodejs v15+.
          - os: windows-latest
            node: 12
          - os: windows-latest
            node: 14

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: node --version
      - run: npm --version

      - name: Install npm dependencies
        run: npm install # switch to `ci` when Node.js 6.x is dropped

      - name: Run tests
        run: npm test
